local Constants = require('src.constants.constants')
local Services = require('src.services.services')

local ScenesService = Services.scenes
local ScenesConst = Constants.scenes

function init(self)
	ScenesService:init()
end

function on_message(self, message_id, message, sender)
	ScenesService:on_init(message_id, function ()
		ScenesService:switch_to_scene(ScenesConst.scenes.start, nil)
	end)
end
